hard_tabs = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2021"

# Below are unstable features, requiring nightly rustfmt
unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
wrap_comments = true
